# Generated by Django 5.0.2 on 2024-02-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='assets',
            field=models.CharField(choices=[('Dekstop', 'Dekstop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('CPU', 'CPU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_system.users'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='assigned_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_system.agent'),
        ),
    ]
